In [8]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('tweets.db')

# Query the tweet_observations table and load it into a pandas DataFrame
query = "SELECT * FROM tweet_observations"
tweet_df = pd.read_sql_query(query, conn)

# Display the first few rows of the dataframe
tweet_df.head()

,id,tweet_id,user_id,observed_at,delta_seconds,user_followers_count,user_following_count,favorite_count,retweet_count,reply_count,quote_count,bookmark_count,view_count
0,1,1901838425566617662,1841667777322745857,1742268591,2,15,446,0,0,0,0,0,0
1,2,1901838421485580348,1286497692416380928,1742268591,3,647,1106,0,0,0,0,0,0
2,3,1901838412556185864,1826050097769234432,1742268591,5,60,1765,0,0,0,0,0,0
3,4,1901838411087954313,1886960193558163456,1742268591,5,76,204,0,0,0,0,0,0
4,5,1901838403077132706,1401171905348964357,1742268591,7,1870,710,0,0,0,0,0,0

In [9]:
# group by tweet_id and count the number of observations
grouped = tweet_df.groupby('tweet_id').size().reset_index(name='count')
# sort by count in descending order
grouped = grouped.sort_values(by='count', ascending=False)
grouped.head()

               tweet_id  count
0   1901838393606332880      3
9   1901838481778708978      3
1   1901838397494468973      3
15  1901838499461914664      3
14  1901838497604071753      3